eureka:
  client:
    service-url:
      defaultZone: http://www.mll.com:8761/eureka/
spring:
  application:
    name: security
  druid:
    url: jdbc:mysql:///mll?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    #最大链接数
    maxActive: 30
    #最小链接数
    minIdle: 5
    #获得链接的最大等待时间
    maxWait: 10000
  security:
    user:
      name: xmcc
      password: xmcc

server:
  port: 9004
xmcc:
  security:
    browser:
      loginPage: /demo_login.html
      loginType: JSON
