eureka:
  client:
    service-url:
      defaultZone: http://www.mll.com:8761/eureka/
spring:
  application:
    name: order
  druid:
    url: jdbc:mysql:///mll?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    #最大链接数
    maxActive: 30
    #最小链接数
    minIdle: 5
    #获得链接的最大等待时间
    maxWait: 10000
  freemarker:
    template-loader-path: classpath:/templates/  #模板存放的路径，默认路径也是这个
    cache: false #不开启缓存，不然模板数据不会实时更新，以后静态页面的时候可以开启
    charset: UTF-8
    check-template-location: true #检查模板路径是否正确
    content-type: text/html
    expose-request-attributes: true #设定所有request的属性在merge到模板的时候，是否要都添加到model中,可以理解为模板是否可以在request作用域中取数据
    expose-session-attributes: true #同上
    allow-request-override: false #指定request作用域数据是否可以覆盖model中数据
    suffix: .ftl #后缀名
  redis:
    host: 192.168.1.114
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 6000
    database: 0
server:
  port: 9002
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
